version: '2'

services:
  bot:
    image: slagick:latest
    build: .
    environment:
    - SLAGICK_API_TOKEN
    - SLAGICK_DB_CONFIG
    links:
    - db
  db:
    image: 'postgres:9.6.2'
    ports:
    - '5432:5432'
