version: '2'

services:
  bot:
    image: slagick:latest
    build: .
    environment:
    - SLAGICK_API_TOKEN
    - SLAGICK_DB_CONFIG
    - SLAGICK_DEBUG=false
    links:
    - db
    restart: always
  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
    - 5432:5432
